### ISSUE TITLE
Admin privileges required?

### ISSUE THREAD

**Issue by mmdevcodes** [spikespaz/vscode-smoothtype#1]
When enabling the extension I get the message:

> Run VS Code with admin privileges so the changes can be applied.

Is this required? When using vscode in workplace environments it's not always possible to use admin privileges.

**Comment by spikespaz** [comment]
The extension modifies core files, so yes, administrator privileges are required. This extension is **extremely** alpha, WIP, or whatever you want to call it, and it is basically the bare minimum required to be functional. Please bear with me as I make this extension more stable and better at what it's supposed to do.

Simply running VS Code with admin privileges once should be enough. Just right click the icon and "Run as Administrator". Run the command to enable it, and you should be set from there on. This will need to be applied again after each VS Code update.
