### ISSUE TITLE
Invalid path?

### ISSUE THREAD

**Issue by ghost** [spikespaz/vscode-smoothtype#10]
Hello, when I execute the command `Reload Smooth Typing` I get the following error:

> Failed to reload Smooth Typing.

I investigated your source code and found out that the file `"/vs/workbench/electron-browser/bootstrap/index.html"` didn't exist in the first place!

https://github.com/spikespaz/vscode-smoothtype/blob/5a163b8a63d55da3b39aeac073d8d8d6238246bc/extension.js#L23

I searched for another entry point to write the css custom code from https://github.com/spikespaz/vscode-smoothtype/blob/5a163b8a63d55da3b39aeac073d8d8d6238246bc/extension.js#L30-L33

I found this (for VSCode Version 1.28.1):

On my Mac (Mojave 10.14):
`/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css`

On my Windows 10 VM:
`C:\Users\XX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css`

On my Linux / Fedora 26 (4.11.8 x86_64) VM:
`/usr/share/code/resources/app/out/vs/workbench/workbench.main.css`

When placing `.cursor{transition: all 80ms}` at the end of the file, it worked.

Hope it help !

**Comment by spikespaz** [comment]
Thanks for all of the extra information! This should be fixed in d8fc9d3. If it isn't, let me know, and I will reopen the issue.
