### ISSUE TITLE
Integrated terminal support?

### ISSUE THREAD

**Issue by Phunky** [spikespaz/vscode-smoothtype#7]
Can this be enabled for integrated terminal also? 

I'm guessing it could be a bit odd in certain situations and might need separate config from editor windows.

**Comment by spikespaz** [comment]
AFAIK this isn't possible. I will take a closer look though.

**Comment by spikespaz** [comment]
Nope, not possible because the Integrated Terminal is some kind of HTML5 + JS canvas that emulates XTerm.
